/**
 * Forge Automatically Generated TypeScript API
 * Do not edit this file manually.
 */

export interface InvokeDetailedOptions {
  detailed?: boolean;
  trace?: boolean;
}

export interface ForgeClipboardApi {
  clear(): Promise<Record<string, unknown>>;
  read(): Promise<Record<string, unknown>>;
  write(text: string): Promise<Record<string, unknown>>;
}

export interface ForgeDialogApi {
  folder(title?: string, directory?: string): Promise<Record<string, unknown>>;
  open(title?: string, directory?: string, filters?: any[], multiple?: boolean): Promise<Record<string, unknown>>;
  save(title?: string, directory?: string, file_name?: string, filters?: any[]): Promise<Record<string, unknown>>;
}

export interface ForgeMenuApi {
  check(item_id: string, checked?: boolean): Promise<Record<string, unknown>>;
  clear(): Promise<boolean>;
  disable(item_id: string): Promise<Record<string, unknown>>;
  enable(item_id: string): Promise<Record<string, unknown>>;
  get(): Promise<any[]>;
  set(items: any[]): Promise<any[]>;
  trigger(item_id: string, payload?: Record<string, unknown>): Promise<Record<string, unknown>>;
  uncheck(item_id: string): Promise<Record<string, unknown>>;
}

export interface ForgeTrayApi {
  hide(): Promise<boolean>;
  is_visible(): Promise<boolean>;
  set_icon(icon_path: string): Promise<string>;
  set_menu(items: any[]): Promise<any[]>;
  show(): Promise<boolean>;
  state(): Promise<Record<string, unknown>>;
  trigger(action: string, payload?: Record<string, unknown>): Promise<Record<string, unknown>>;
}

export interface ForgeWindowApi {
  broadcast(event: string, payload?: unknown, exclude_self?: boolean): Promise<Record<string, unknown>>;
  send(target_label: string, event: string, payload?: unknown): Promise<Record<string, unknown>>;
}

export interface ForgeApi {
  invoke(command: string, args?: Record<string, unknown>): Promise<unknown>;
  invokeDetailed(command: string, args?: Record<string, unknown>, options?: InvokeDetailedOptions): Promise<unknown>;
  on(eventName: string, handler: (payload: unknown) => void): unknown;
  once(eventName: string, handler: (payload: unknown) => void): unknown;
  off(eventName: string, handler: (payload: unknown) => void): unknown;
  clipboard: ForgeClipboardApi;
  dialog: ForgeDialogApi;
  menu: ForgeMenuApi;
  tray: ForgeTrayApi;
  window: ForgeWindowApi;
  apply_native_selection(item_id: string, checked?: boolean): Promise<Record<string, unknown>>;
  asset_url(path: string): Promise<string>;
  clear_user_attention(): Promise<void>;
  close_all(): Promise<number>;
  deep_link_open(url: string): Promise<Record<string, unknown>>;
  deep_link_protocols(): Promise<Record<string, unknown>>;
  deep_link_state(): Promise<Record<string, unknown>>;
  delete(path: string, recursive?: boolean): Promise<void>;
  disable(): Promise<boolean>;
  enable(): Promise<boolean>;
  exists(path: string): Promise<boolean>;
  exit(): Promise<void>;
  exit_app(): Promise<void>;
  get_base_path(): Promise<unknown>;
  get_battery_info(): Promise<Record<string, unknown>>;
  get_cursor_screen_point(): Promise<Record<string, unknown>>;
  get_cwd(): Promise<string>;
  get_env(key: string, default?: string): Promise<string>;
  get_info(): Promise<Record<string, unknown>>;
  get_monitors(): Promise<any[]>;
  get_platform(): Promise<string>;
  get_primary_monitor(): Promise<Record<string, unknown>>;
  get_version(): Promise<string>;
  info(): Promise<Record<string, unknown>>;
  is_dir(path: string): Promise<boolean>;
  is_enabled(): Promise<boolean>;
  is_file(path: string): Promise<boolean>;
  list(path: string, include_hidden?: boolean): Promise<any[]>;
  list_dir(path: string, include_hidden?: boolean): Promise<any[]>;
  mkdir(path: string, parents?: boolean): Promise<void>;
  notification_history(limit?: number): Promise<any[]>;
  notification_notify(title: string, body: string, icon?: string, app_name?: string, timeout?: number): Promise<Record<string, unknown>>;
  notification_state(): Promise<Record<string, unknown>>;
  on_resume(callback: unknown): Promise<void>;
  on_suspend(callback: unknown): Promise<void>;
  open_file(path: string): Promise<void>;
  open_path(path: string): Promise<Record<string, unknown>>;
  open_url(url: string): Promise<Record<string, unknown>>;
  platform(): Promise<string>;
  position_bottom_left(label?: string, margin?: number): Promise<Record<string, unknown>>;
  position_bottom_right(label?: string, margin?: number): Promise<Record<string, unknown>>;
  position_center(label?: string): Promise<Record<string, unknown>>;
  position_top_left(label?: string, margin?: number): Promise<Record<string, unknown>>;
  position_top_right(label?: string, margin?: number): Promise<Record<string, unknown>>;
  position_tray_anchor(label?: string): Promise<Record<string, unknown>>;
  read(path: string, max_size?: number): Promise<string>;
  read_binary(path: string, max_size?: number): Promise<unknown>;
  register(accelerator: string, callback: unknown): Promise<boolean>;
  relaunch(): Promise<void>;
  request_single_instance_lock(instance_name?: string): Promise<boolean>;
  request_user_attention(is_critical?: boolean): Promise<void>;
  reveal_in_folder(path: string): Promise<Record<string, unknown>>;
  set_action_handler(handler: Record<string, unknown>): Promise<void>;
  set_progress_bar(progress: number): Promise<void>;
  task_cancel(task_id: string): Promise<boolean>;
  task_list(): Promise<unknown[]>;
  task_start(name: string, interval?: number): Promise<string>;
  task_status(task_id: string): Promise<Record<string, unknown>>;
  unregister(accelerator: string): Promise<boolean>;
  unregister_all(): Promise<boolean>;
  version(): Promise<string>;
  write(path: string, content: string): Promise<void>;
  write_binary(path: string, content: unknown): Promise<void>;
  ws_close(connection_id: string, code?: number, reason?: string): Promise<Record<string, unknown>>;
  ws_connect(url: string, headers?: Record<string, unknown>, protocols?: string[], auto_reconnect?: boolean, reconnect_delay?: number, max_reconnect_attempts?: number): Promise<Record<string, unknown>>;
  ws_list(): Promise<Record<string, unknown>>;
  ws_send(connection_id: string, data: string): Promise<Record<string, unknown>>;
  ws_send_binary(connection_id: string, data_b64: string): Promise<Record<string, unknown>>;
  ws_state(connection_id: string): Promise<Record<string, unknown>>;
}

export declare function isForgeAvailable(): boolean;
export declare function getForge(): ForgeApi;
export declare function invoke(command: string, args?: Record<string, unknown>): Promise<unknown>;
export declare function invokeDetailed(command: string, args?: Record<string, unknown>, options?: InvokeDetailedOptions): Promise<unknown>;
export declare function on(eventName: string, handler: (payload: unknown) => void): unknown;
export declare function once(eventName: string, handler: (payload: unknown) => void): unknown;
export declare function off(eventName: string, handler: (payload: unknown) => void): unknown;
export declare const forge: ForgeApi;
export default forge;
